import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css"
import LinkButton from "@/components/main/link-button";
import { Toaster } from "@/components/ui/toaster";

const InterFont = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${InterFont.className} antialiased`}>
        <LinkButton link="/" className="fixed top-2 left-2" variant="outline">
          Back
        </LinkButton>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
