// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupOldUploads(arg1) {
  return window['go']['app']['App']['CleanupOldUploads'](arg1);
}

export function DeleteUpload(arg1, arg2) {
  return window['go']['app']['App']['DeleteUpload'](arg1, arg2);
}

export function GetAllUploadedFiles(arg1) {
  return window['go']['app']['App']['GetAllUploadedFiles'](arg1);
}

export function GetFileUpload(arg1) {
  return window['go']['app']['App']['GetFileUpload'](arg1);
}

export function GetUploadedFiles(arg1) {
  return window['go']['app']['App']['GetUploadedFiles'](arg1);
}

export function GetUserId() {
  return window['go']['app']['App']['GetUserId']();
}

export function GetUsername() {
  return window['go']['app']['App']['GetUsername']();
}

export function SetUsername(arg1) {
  return window['go']['app']['App']['SetUsername'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['app']['App']['UploadFile'](arg1, arg2);
}

export function ValidateFile(arg1, arg2) {
  return window['go']['app']['App']['ValidateFile'](arg1, arg2);
}
