// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {handlers} from '../models';

export function CleanupOldUploads(arg1:time.Duration):Promise<void>;

export function DeleteUpload(arg1:string,arg2:string):Promise<void>;

export function GetAllUploadedFiles(arg1:string):Promise<Array<handlers.FileUpload>>;

export function GetFileUpload(arg1:string):Promise<handlers.FileUpload>;

export function GetUploadedFiles(arg1:string):Promise<Array<handlers.FileUpload>>;

export function GetUserId():Promise<string>;

export function GetUsername():Promise<string>;

export function SetUsername(arg1:string):Promise<void>;

export function UploadFile(arg1:string,arg2:Array<number>):Promise<void>;

export function ValidateFile(arg1:number,arg2:string):Promise<void>;
